### ISSUE TITLE
SassError: Undefined variable: "$grid-gutter-width".

### ISSUE THREAD

**Issue by frani** [entozoon/spacing-bootstrap-3#1]
hello !

```
./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/App.scss)
SassError: Undefined variable: "$grid-gutter-width".
        on line 13 of node_modules/spacing-bootstrap-3/_spacing.scss
        from line 12 of src/assets/style/sass/materialize.scss
        from line 1 of /Users/franciscoinnocenti/git/SJI/form-new-prop/src/App.scss
>> $spacer:   $grid-gutter-width * .5 !default;
   -----------^
```

there is a way to add $grid-gutter-width with a default value if does not exists ?

**Comment by entozoon** [comment]
Hey there, I've added a default value for you in [version 1.02](https://github.com/entozoon/spacing-bootstrap-3/commit/21018a134aa09fe75b9104afce0897a61461cfc2).
Ideally it would import those values from the Bootstrap [vars file](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss) beforehand, but no worries, I've added defaults.
Good luck!
(Didn't know anyone was using Bootstrap 3 in 2020!)

**Comment by frani** [comment]
Thanks!
We don't using Bootstrap 3, either bootstrap on current project
We just need this SASS module to add with our SASS modules.
very useful by the way 
Regrads!
